#!/bin/sh
export ETC="$HOME/etc"
export SDL_VIDEO_ALLOW_SCREENSAVER=1
export TERMINAL="sakura"

#xterm -geometry 132x80 &
#exec twm

cancel_or_not()
{
	local delay="$1"; shift
	local command="$1"; shift
	if zenity \
		--timeout "$delay" --question \
		--text "Vou iniciar o $command\n$delay segundos pra cancelar..." \
		--ok-label "Cancelar" \
		--cancel-label "Rodar Agora"
	then
		echo "Cancelado."
	else
		echo "Chamando o $command com parametros ($*) (sqn)"
		"$command" "$@"
	fi
}

xcape -e 'Caps_Lock=Escape'
true && (
	sleep 1
	#gkrellm &
	if test -n "$(ls /wd/)"; then
		sleep 1
		cancel_or_not 7 transmission-gtk &
	fi
	#sleep 1
	#cancel_or_not 8 /opt/Signal/signal-desktop &
	sleep 1
	cancel_or_not 9 pidgin &
) &
exec mate-session
