#!/bin/bash
if test -z "$freemyip_domain" -o -z "$freemyip_token"; then
	echo 'Please define $freemyip_domain and $freemyip_token'
	exit
fi

test -z "$ETC" && ETC="$HOME/etc"
. "$ETC/bash/show.sh"
cd "$(dirname "$0")" || exit
last_ip="$(cat last_ip.txt)"
curr_ip="$(show ip)"
if test "$last_ip" == "$curr_ip"; then
	echo "IP address $curr_ip up to date"
else
	curl_rc="$(curl "https://freemyip.com/update?token=$freemyip_token&domain=$freemyip_domain")"
	if test "$curl_rc" == "OK"; then
		echo "$curr_ip" > last_ip.txt
		echo "IP address updated to $curr_ip"
	else
		echo "IP address not updated:"
		echo "$curl_rc"
	fi
fi
