#!/bin/bash
# vim600:ft=sh:foldmethod=marker:foldmarker={,}:

function log()
{
	echo "`date`: $*" \
	>> "/tmp/`basename "$0"`.log"
}

function add_to_path()
{
	local end='tail'
	while test -n "$1"; do
		case "$1" in
			-t)
				end='tail'
			;;
			-h)
				end='head'
			;;
			*)
			if test -d "$1"; then
				if
					! expr match "$PATH"    "$1:"  >/dev/null &&
					! expr match "$PATH" ".*:$1:"  >/dev/null &&
					! expr match "$PATH" ".*:$1$"  >/dev/null
				then
					if test "$end" == 'tail'; then
						export PATH="$PATH:$1"
					else
						export PATH="$1:$PATH"
					fi
				fi
			else
				echo "\"$1\": not a directory"
			fi
			;;
		esac
		shift
	done
}

