#!/bin/bash
# vim600:ft=sh:foldmethod=marker:foldmarker={,}:

function log()
{
	echo "`date`: $*" \
	>> "/tmp/`basename "$0"`.log"
}

function add_to_path()
{
	local position='tail'
	while test -n "$1"; do
		local dir="$1"
		case "$dir" in
			-t)
				position='tail'
			;;
			-h)
				position='head'
			;;
			*)
			if test -d "$dir"; then
				if
					! expr match "$PATH"    "$dir:"  >/dev/null &&
					! expr match "$PATH" ".*:$dir:"  >/dev/null &&
					! expr match "$PATH" ".*:$dir$"  >/dev/null
				then
					if test "$position" == 'tail'; then
						export PATH="$PATH:$dir"
					else
						export PATH="$dir:$PATH"
					fi
				fi
			else
				echo "\"$dir\": not a directory"
			fi
			;;
		esac
		shift
	done
}

